{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.denglongfei",
    "module": "activityGuard",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "activityGuard-1.1.0.jar",
          "url": "activityGuard-1.1.0.jar",
          "size": 110546,
          "sha512": "201e52e746ef6a66dd0a13baf8049d3af7150b64fb1c8a142ec9031fedb570cef004bc18eb78c7a94714d7875d905fdad250b2315ec0c20bfe736ad6f484d3bc",
          "sha256": "038b18b0f193c1e71099c71db3f1b8ca8b69331a5ca108da499393a086b80968",
          "sha1": "f08bb31853b3cb7bcd99c459acd2690e22a4456d",
          "md5": "4a086eb8851c9d29c88a9f57c7d96891"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "activityGuard-1.1.0.jar",
          "url": "activityGuard-1.1.0.jar",
          "size": 110546,
          "sha512": "201e52e746ef6a66dd0a13baf8049d3af7150b64fb1c8a142ec9031fedb570cef004bc18eb78c7a94714d7875d905fdad250b2315ec0c20bfe736ad6f484d3bc",
          "sha256": "038b18b0f193c1e71099c71db3f1b8ca8b69331a5ca108da499393a086b80968",
          "sha1": "f08bb31853b3cb7bcd99c459acd2690e22a4456d",
          "md5": "4a086eb8851c9d29c88a9f57c7d96891"
        }
      ]
    }
  ]
}
